import { streamText } from "ai";
import { Router } from "express";
import myModels from "../config/ai";

const aiRouter = Router();

aiRouter.post("/inference", async (req, res) => {
  try {
    if (!req.body.messages) {
      res.status(400).send("Messages not provided");
      return;
    }

    // Set headers for SSE (Server-Sent Events)
    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    });
    // res.setHeader("Content-Type", "text/event-stream");

    let { messages } = req.body;

    const kitArchModel = await Bun.file(
      "/Users/anthonydemattos/auto-bim/train/dataset/kit_architectural.ifc"
    ).text();
    const tableAndChairsModel = await Bun.file(
      "/Users/anthonydemattos/auto-bim/train/dataset/tabel_chairs.ifc"
    ).text();
    const ifcOntology = await Bun.file(
      "/Users/anthonydemattos/auto-bim/express-app/app/routes/ifc_spec.txt"
    ).text();
    const cubeModel = await Bun.file(
      "/Users/anthonydemattos/auto-bim/train/dataset/cube.ifc"
    ).text();

    const result = await streamText({
      model: myModels["claude-3.5-sonnet"],
      system: `<ifc_info>
The assistant can create and reference artifacts of ifc files during conversation. IFC (Industry Foundation Classes) is a data model that describes building and construction industry data. It is mainly used in the design, construction, and operation of buildings and infrastructure. The assistant can generate IFC models based on the input provided by the user. The assistant can also provide information about the IFC data model and its applications in the AEC industry.
</ifc_info>

<example_ifc>
<ifc>
${cubeModel}
</ifc>
</example_ifc>

<thinking_info>
Before the assistant reponds to the user, it takes some time to think/reason out a plan for its response. The assistant uses <thinking></thinking> tags to wrap its thought process.
Thinking tags are ONLY used at the beginning of the assistants response and no where else.
The assistant takes its time to think thoroughly about the user's input and then generates a response. The assistant breaks down the problem into steps.
</thinking_info>

<davinci_info>
You are an AI named Da Vinci. Your named after Leonardo Da Vinci because he was one of the greatest engineers to ever live. 
You have been trained on all of the digital information generated by humanity, which makes you a sort of digital super intelligence. 
You have seen all of the .IFC (Industry Foundation Classes) files that have been generated, which makes you an expert in the field  of architecture, engineering, and construction. 
You are an expert at creating design engineer specifications, drawings, and models for buildings and infrastructure. In your output you are able to generate .IFC models, which are used by architects, engineers, and 
construction professionals to design and construct buildings and infrastructure. 
</davinci_info>`,
      temperature: 0,
      messages,
    });

    for await (const textPart of result.textStream) {
      res.write(
        `event: message\ndata: ${JSON.stringify({ chunk: textPart })}\n\n`
      );
    }

    res.write("event: DONE\ndata: \n\n");
    res.end();
  } catch (err) {
    console.error(err);
    res.status(500).send("Internal server error");
  }
});

export default aiRouter;
